### ISSUE TITLE
Add Documentation for config options (confusion about trailing slash)

### ISSUE THREAD

**Issue by Datamance** [socialwifi/jsonapi-requests#16]
Hi, 

IMO this shouldn't happen. I'm not sure what JSON:API spec says.

Here's what I get with the library:
`127.0.0.1 - - [31/Mar/2017 13:43:47] "GET /api/v1/products/ HTTP/1.1" **404** -`

Here's the code that's producing that:

```
api = Api.config({
    'API_ROOT': 'http://localhost:5000/api/v1'
})

nps_endpoint = api.endpoint('nps')
products_endpoint = api.endpoint('products')

# trailing slash added here?
pprint(products_endpoint.get())

```

It looks like this library refuses to play nice with [flask_restless](https://github.com/jfinkels/flask-restless), which IMO is a show-stopper.

This code works perfectly fine in testing the GET part of the API:
```
products_url = 'http://localhost:5000/api/v1/products'
headers = {
    'Content-Type': 'application/json',
    'Accept': 'application/vnd.api+json'
}

response = requests.get(products_url, headers=headers)
assert response.status_code == 200
pprint(response.json())
```

Proof the manager log:
```
127.0.0.1 - - [31/Mar/2017 13:57:49] "GET /api/v1/products HTTP/1.1" 200 -
```

Any idea why the same exact url hit from this library would return a different status code/results?

**Comment by Datamance** [comment]
OK, so I can see what's happening here.

Your library is adding a trailing slash after the resource name. This is not necessarily part of the JSON:API spec, but flask-restless happens to be opinionated about it. @jfinkels might want to comment on this?

In any case, when I change the second suite of test code (just the requests library plus appropriate headers) to add a trailing slash, I get the same 404. Otherwise, I get a beautiful JSON:API formatted response with a status code of 200.

**Comment by Datamance** [comment]
OK, never mind, [problem solved](https://github.com/socialwifi/jsonapi-requests/blob/master/jsonapi_requests/request_factory.py#L50)

You should just have all of these options in documentation.

**Comment by kramarz** [comment]
We just don`t have any documentation yet, assuming that if it would be needed someone would ask for it (as you did). Maintaining documentation slows down development. We will write more detailed documentation when we reach some stability (aka version 1.x.x). For now i have documented configuration options as you asked: https://github.com/socialwifi/jsonapi-requests/wiki/Configuration . I have also added link to Readme.

**Comment by evandavey** [comment]
The ORM endpoint still adds a trailing slash:

in orm/api_model.py
```
    @property
    def endpoint(self):
        return self._options.api.endpoint('{}/{}/'.format(self._options.type, self.id))
```

**Comment by jgoclawski** [comment]
@evandavey right, thanks! I've opened an issue for that and will fix it in a moment.
