### ISSUE TITLE
Using ORM to get a list

### ISSUE THREAD

**Issue by evandavey** [socialwifi/jsonapi-requests#21]
How do I use the ORM to get an object list?

The only way I've deduced is by calling api.endpoint('...').get(), looping through the response data to get the id, then calling the from_id method (but this will do multiple hits on the API).  I couldn't figure out a way to use the from_response_content method.

```python
designs = api.endpoint('designs').get()
for entry in designs.data:
    design = Design.from_id(entry.id)
    print(design.name)
```

**Comment by kramarz** [comment]
from response for now only works for single object response. As a workaround you can run:
```python
designs = api.endpoint('designs').get()
for entry in designs.data:
    design = Design(raw_object=entry)
    print(design.name)
```

**Comment by evandavey** [comment]
OK thanks, will give that a try.  Looks like saving isn't supported yet either so I have to do that via the endpoint methods?

**Comment by kramarz** [comment]
@evandavey We have added both: getting list and saving objects(#23) Next step will be probably filtering/including related objects in #25

**Comment by evandavey** [comment]
Great, thanks!

**Comment by evandavey** [comment]
Trying this I get

```
designs = Design.get_list()
AttributeError: type object 'Design' has no attribute 'list_endpoint'
```

**Comment by jgoclawski** [comment]
@evandavey please open a new issue describing your problem. Please include your full configuration,  so I can try to reproduce the error.
As you can see in [our tests](https://github.com/socialwifi/jsonapi-requests/blob/e11a7412121f06b0a4b33224ffa9b3a91876d5bd/tests/test_orm.py#L260) we have a test for getting a list and it works. 
It might be related to #22 if you're manually modifying internal values (`_options` in this case). You could probably try to further hack it, by doing manually something like [here](https://github.com/socialwifi/jsonapi-requests/blob/master/jsonapi_requests/orm/api_model.py#L21), but I still don't recommend it.

**Comment by evandavey** [comment]
Yes, I followed the hack and it worked, so it must be related to #22.  Do you still want a new issue created?
