### ISSUE TITLE
Dependency to tenacity breaks package

### ISSUE THREAD

**Issue by Kingsy** [socialwifi/jsonapi-requests#53]
Since the update of tenacity to version 8.0.0 this package is now broken.
We can see in the tenacity release notes

```Removed BaseRetrying.call: was long time deprecated and produced DeprecationWarning```

Which in turn breaks this line in jsonapi-requests

https://github.com/socialwifi/jsonapi-requests/blob/master/jsonapi_requests/request_factory.py#L34
Manifesting with the following error

```Retrying object has no attribute call```

This can be mitigated for now by locking the tenacity version to version 7.0.0.

Can I suggest either you add this restriction to https://github.com/socialwifi/jsonapi-requests/blob/master/base_requirements.txt - until this issue is resolved.

Thanks

**Comment by jgoclawski** [comment]
@Kingsy Hi, thanks for the info. Would you mind sending a Pull Request? Plan minimum is, as you said, to pin the version below 8. But if you know how to make the package work with >8, that would be even better.
