### ISSUE TITLE
How to modify the header?

### ISSUE THREAD

**Issue by oefterdal** [socialwifi/jsonapi-requests#58]
How do I modify the header so I can add a Bearer?

**Comment by oefterdal** [comment]
I created a new class and it worked, but not sure if its the proper way to do it. 

`class Bearer(requests.auth.AuthBase):
    def __call__(self, r):
        r.headers['Authorization'] = f'Bearer {settings.access_token}'
        return r`

**Comment by jgoclawski** [comment]
The AUTH parameter can be a custom class, compatible with `requests` (https://docs.python-requests.org/en/latest/user/authentication/).
See example here: https://github.com/socialwifi/jsonapi-requests#authorization-http-header-forwarding-in-flask-application

So in your case, you'd use your new class like this:
```
import jsonapi_requests

api = jsonapi_requests.Api.config({
    'API_ROOT': 'https://localhost/api/2.0',
    'AUTH': Bearer(),
})
```
